language: minimal
addons:
  ssh_known_hosts: git.balena-cloud.com
after_success:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in deploy/deploy_key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git checkout master
  - git remote add balena gh_eliecharra@git.balena-cloud.com:gh_eliecharra/pivario0.git
  - git push balena
