language: minimal
addons:
  ssh_known_hosts: git.balena-cloud.com
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in deploy/deploy_key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
