language: minimal
addons:
  ssh_known_hosts: git.balena-cloud.com
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in deploy/deploy_key.enc -out deploy/deploy_key -d
deploy:
  provider: script
  script: bash deploy/deploy.sh
  on:
    branch: master
